version: '2'

volumes:
  hub_data: {}
  hub_media: {}
  postgres_data: {}
  postgres_backup: {}
  redis_data: {}

services:
  postgres:
    restart: always
    build: ./compose/postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - postgres_backup:/backups
    env_file: 
      - .env

  django:
    restart: always
    environment: 
      - PYTHONPATH=/app/openbadge-server
      - DJANGO_SETTINGS_MODULE=config.settings.production
    env_file:
      - .env
    build:
      context: .
      dockerfile: ./compose/django/Dockerfile
    expose:
      - "5000"
    user: django
    depends_on:
      - postgres
    links:
      - postgres
      - redis
    volumes:
      - hub_media:/media/
      - hub_data:/media/data/
      - /www/static
    command: /gunicorn.sh

  nginx:
    build: ./compose/nginx
    restart: always
    depends_on:
      - django
    volumes_from:
      - django
    links:
      - django
    ports:
      - "0.0.0.0:80:80"
  redis:
    restart: always
    image: redis:latest
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data


